### ISSUE TITLE
Weitere Anreden

### ISSUE THREAD

**Issue by fc-smohr** [oboehm/jfachwert#24]
In der Klasse src/main/kotlin/de/jfachwert/formular/Anrede.kt können nun weitere Anrede-Schlüssel aus dem GDV ergänzt werden, siehe http://www.gdv-online.de/vuvm/bestand/rel2023/ds0100.htm
Das sind konkret:
- 7 = Damen
- 8 = Herren

Ich hätte direkt einen PR aufgemacht, das scheint aber über die Web-Gui nicht (trivial wie GitLab) machbar oder nicht erlaubt zu sein.

**Comment by oboehm** [comment]
Hallo Sergius,

danke für den Hinweis - werde ich bei Gelegenheit ergänzen.

mfg
oli b.

**Comment by oboehm** [comment]
Mit 5.4.2 aktualisiert
