### ISSUE TITLE
Steuernummer Prüfziffer Validierung greift nur bei 11 stelligen Steuernummern 

### ISSUE THREAD

**Issue by Loki-Afro** [oboehm/jfachwert#6]
In `de.jfachwert.steuer.Steuernummer#verify` greift die validierung nur bei 11 stellungen Steuernummern.
Leider weiß ich nicht welches Verfahren angewandt werden sollte bei 10 Stelligen Stauernummern ... 

Jeodch haben sie bei Wikipedia auch eine Prüfziffer https://de.wikipedia.org/wiki/Steuernummer

**Comment by oboehm** [comment]
Wenn ich das wüsste - ich denke, das hängt vom jeweiligen Bundesland bzw. Steuerbehörde ab, wenn ich http://www.pruefziffernberechnung.de/S/Steuernummer-DE-Berlin.shtml richtig interpretiere.

**Comment by Loki-Afro** [comment]
@oboehm jup, die Seite ist mir auch begegnet ... sowas müsste doch in Gesetzen stehen .... aber eigentlich hab ich keine Ahnung :D

**Comment by oboehm** [comment]
Ich auch nicht sonderlich viel - aber wenn ich es richtig verstehe, sollte die bundesweite Steuerliche Identifikationsnummer die alte Steuernummer ablösen - und die ist 11-stellig.

**Comment by Loki-Afro** [comment]
@oboehm 

zur vollständigkeit habe ich damals noch was zusammen programmiert... 

https://github.com/kaffeekrone/jsteuernummer
